name: nodeTestApp CD
on:
  workflow_run:
    workflow: ["nodeTestApp CI"]
  
jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Pull Docker Image
      run: sudo docker pull prudhvigopasina1999/nodetestapp:latest .

    - name: Delete old Docker container 
      run: sudo docker rm -f nodetestapp-container || true 

    - name: Run Docker Container
      run: sudo docker run -d -p 3000:3001 --name nodetestapp-container prudhvigopasina1999/nodetestapp
