name: NodeTestApp CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest

    steps:
    - name: Cross Checking the code
      uses: actions/checkout@v2

    - name: Set-up Node.js
      uses: actions/checkout@v2
      with:
        node-version: '18.16.0'
        
    - name: Set-up CI
    - run: npm ci
    
    - name: Build the Node.js application
    - run: npm run build

    # - name: Running the Test Cases
    # - run: npm test
      
  windows-build:
    runs-on: ubuntu-latest

    steps:
    - name: Cross Checking the code
      uses: actions/checkout@v2

    - name: Set-up Node.js
      uses: actions/checkout@v2
      with:
        node-version: '18.16.0'

    - name: Set-up CI
    - run: npm ci
    
    - name: Build the Node.js application
    - run: npm run build

    # - name: Running the Test Cases
    # - run: npm test
